### ISSUE TITLE
How to get Eszett german character?

### ISSUE THREAD

**Issue by lwhiteley** [UbuntuBudgie/QuickChar#8]
What ive tried typing: 
- s
- S
- b 
- B
- ss (doesnt accept two letters)

all of these do not show  `ß`.

Is this a bug, not accounted for yet or is there another way to show this?

 actual correlation: `ß` => `ss`

**Comment by Jacob-Vlijm** [comment]
It's not actually a bug, but nevertheless a useful suggestion. The characters of QuickChar aren't hardcoded, but stored in a file: `/usr/share/quickchar/chardata`. I'll update the file with your suggestion, but since we've just had 22.04, it won't appear immediately in the repos.
For the time being though, you could find the edited file from [here](https://raw.githubusercontent.com/UbuntuBudgie/QuickChar/master/data/chardata) (in a minute, after I pushed it), including the ß. If you copy the text, open the chardata file (`sudo -i gedit /usr/share/quickchar/chardata`) and replace the content with the new content, restart Quickchar, you're done.

![image](https://user-images.githubusercontent.com/8932980/166145797-ff498b59-646a-41f5-8ede-88d93d8fb212.png)

**Comment by lwhiteley** [comment]
Awesome thanks for the quick reply.

This works with one exception in my case.

Copying the content didnt work as it copied `ss` (for some reason) instead of the actual charater.

So i downloaded the file and ran
```
sudo mv ~/Downloads/chardata.txt /usr/share/quickchar/chardata
```

After restarting Quickchar then i can now see the ß char.

Thanks for the help!

Edit:
maybe copied too early https://github.com/UbuntuBudgie/QuickChar/commit/6da3a4c0675a182777cedfbbd2899affb355f486 ?

**Comment by Jacob-Vlijm** [comment]
Ah, probably. If you run into anything that's missing, feel free to request.
